### ISSUE TITLE
Custom Domain URI

### ISSUE THREAD

**Issue by michaelaguiar** [Superbalist/laravel-google-cloud-storage#13]
Looks like I can only set a domain to go directly to a bucket.  Because of this, the ->url() method will return https://domain.com/domain.com/file.ext. -- the second domain.com being the bucket.

If I try to do domain.com/bucket_name/file.ext, I get permission denied even though the file is public.

Am I missing something?

**Comment by evinkuraga** [comment]
@michaelaguiar In your custom domain remove the s from httpS

Similar issue here. I get http://custom.domain.com/BUCKET/path/to/file.ext
Any way to remove the bucket name from the url entirely. Even if I put null in the bucket config, I still get an empty "/", which gives me:
http://customdomain.com//path/to/file.ext , which fails to load the file due to the incorrect absolute path.

**Comment by victorybiz** [comment]
@evinkuraga My bucket name is a custom domain `static.domain.com` which point to directly to my bucket. 

Setting `GOOGLE_CLOUD_STORAGE_API_URI=null`,  `$disk->url('my_file.ext');` returns correctly with `https://storage.googleapis.com/static.domain.com/my_file.ext`

When  this is set `GOOGLE_CLOUD_STORAGE_API_URI=http://static.domain.com`, it returns `http://static.domain.com/static.domain.com/my_file.ext` which is not valid instead of `http://static.domain.com/my_file.ext`.

Any fix?

**Comment by ajayfroiden** [comment]
@victorybiz You can set GOOGLE_CLOUD_STORAGE_API_URI=http://static.domain.com/

/ at the end

**Comment by michaelaguiar** [comment]
Thanks everyone, this issue is closed.
